services:
  - type: web
    name: smart-parking-api
    runtime: docker
    branch: main
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
