import React,{useEffect,useState}from'react';
const API='http://localhost:8081/api';
async function req(path,options={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json'},...options});const x=await r.json();if(!r.ok)throw Error(x.message||'Request failed');return x}
function Card({title,value}){return <article className="panel metric"><span>{title}</span><strong>{value}</strong></article>}
export default function App(){
 const [user,setUser]=useState(JSON.parse(localStorage.getItem('sp-user')||'null')),[mode,setMode]=useState('login'),[role,setRole]=useState('USER'),[tab,setTab]=useState('home'),[locations,S]=useState([]),[vehicles,V]=useState([]),[bookings,B]=useState([]),[message,M]=useState(''),[search,Q]=useState(''),[form,F]=useState({});
 const set=(k,v)=>F(old=>({...old,[k]:v})),admin=user?.role==='ADMIN';
 async function load(){S(await req('/parking/locations'+(search?'?search='+encodeURIComponent(search):'')));if(user){if(user.role==='USER'){V(await req('/vehicles?userId='+user.id));B(await req('/bookings/my?userId='+user.id))}else B(await req('/admin/bookings?ownerId='+user.id))}}
 useEffect(()=>{load().catch(e=>M(e.message))},[user,search]);
 async function act(fn){try{M('');await fn();await load()}catch(e){M(e.message)}}
 function login(x){setUser(x);localStorage.setItem('sp-user',JSON.stringify(x));setTab('home')}
 if(!user)return <main className="auth"><section className="panel authbox"><p className="eyebrow">SMART PARKING</p><h1>{mode==='login'?'Welcome back':'Create your account'}</h1><p>Find and manage parking in one simple place.</p>
 {mode==='login'?<><div className="toggle"><button className={role==='USER'?'selected':''} onClick={()=>setRole('USER')}>User</button><button className={role==='ADMIN'?'selected':''} onClick={()=>setRole('ADMIN')}>Provider</button></div><form onSubmit={e=>{e.preventDefault();act(async()=>login(await req('/auth/login',{method:'POST',body:JSON.stringify({...form,role})})))}}><label>Email<input required type="email" onChange={e=>set('email',e.target.value)}/></label><label>Password<input required type="password" onChange={e=>set('password',e.target.value)}/></label><button className="primary">Login</button></form><p>New here? <a onClick={()=>setMode('register')}>Create an account</a></p></>:<form onSubmit={e=>{e.preventDefault();act(async()=>{await req('/auth/register',{method:'POST',body:JSON.stringify({...form,role})});M('Account created. Please log in.');setMode('login')})}}><label>Account type<select onChange={e=>setRole(e.target.value)}><option value="USER">User</option><option value="ADMIN">Parking provider</option></select></label><label>Full name<input required onChange={e=>set('name',e.target.value)}/></label>{role==='ADMIN'&&<><label>Company<input required onChange={e=>set('companyName',e.target.value)}/></label><label>Provider type<select onChange={e=>set('providerType',e.target.value)}>{['Private Parking Provider','Business / Mall','Hotel','Residential Society','Other'].map(x=><option key={x}>{x}</option>)}</select></label></>}<label>Email<input required type="email" onChange={e=>set('email',e.target.value)}/></label><label>Phone<input onChange={e=>set('phone',e.target.value)}/></label><label>Password<input required type="password" onChange={e=>set('password',e.target.value)}/></label><label>Confirm password<input required type="password" onChange={e=>set('confirmPassword',e.target.value)}/></label><button className="primary">Register</button><p><a onClick={()=>setMode('login')}>Back to login</a></p></form>}{message&&<p className="notice">{message}</p>}</section></main>;
 const nav=admin?['home','locations','slots','bookings','users']:['home','find parking','my bookings','my vehicles'];
 return <div className="layout"><header><div><b>🅿 Smart Parking</b><span className="sub">{user.companyName||'Parking made simple'}</span></div><div>{user.name}<button className="outline" onClick={()=>{localStorage.removeItem('sp-user');setUser(null)}}>Log out</button></div></header><nav>{nav.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav><main className="content"><h1>{tab==='home'?`Hello, ${user.name}`:tab}</h1>{message&&<p className="notice">{message}</p>}
 {tab==='home'&&<><section className="hero"><h2>{admin?'Manage your parking locations':'Find a place to park'}</h2><p>{admin?'Add locations and slots, and keep track of bookings.':'Search parking nearby, choose a vehicle and book a suitable slot.'}</p><button className="primary" onClick={()=>setTab(admin?'locations':'find parking')}>{admin?'Add location':'Find parking'}</button></section><div className="grid"><Card title={admin?'Bookings':'My bookings'} value={bookings.length}/><Card title={admin?'Locations':'Vehicles'} value={admin?locations.length:vehicles.length}/><Card title="Active bookings" value={bookings.filter(b=>b.status==='ACTIVE').length}/></div>{!admin&&bookings[0]&&<><h2>Recent booking</h2><Booking b={bookings[0]} user={user} action={act}/></>}</>}
 {(tab==='find parking'||tab==='locations')&&<><div className="bar"><input placeholder="Search by parking, city or area" value={search} onChange={e=>Q(e.target.value)}/>{admin&&<button className="primary" onClick={()=>set('showLocation',!form.showLocation)}>+ Add location</button>}</div>{admin&&form.showLocation&&<form className="panel formgrid" onSubmit={e=>{e.preventDefault();act(async()=>{await req('/admin/locations',{method:'POST',body:JSON.stringify({...form,ownerId:user.id})});set('showLocation',false)})}}>{['name','address','city','area','carRate','bikeRate','evRate','description'].map(k=><label key={k}>{k.replace(/([A-Z])/g,' $1')}<input required={k!=='description'} type={k.endsWith('Rate')?'number':'text'} onChange={e=>set(k,e.target.value)}/></label>)}<button className="primary">Save location</button></form>}<div className="grid">{locations.map(l=><article className="panel" key={l.id}><p className="eyebrow">{l.city} · {l.area}</p><h2>{l.name}</h2><p>{l.address}</p><p>Provided by {l.provider||user.companyName}</p><p>{l.available_slots} available of {l.total_slots} · ₹{l.car_rate}/hour (car)</p>{admin?<button className="outline" onClick={()=>{set('selectedLocation',l);setTab('slots')}}>Manage slots</button>:<button className="primary" onClick={()=>{set('selectedLocation',l);setTab('slot selection')}}>View slots</button>}</article>)}</div></>}
 {tab==='slot selection'&&<SlotPicker location={form.selectedLocation} user={user} vehicles={vehicles} run={act}/>}
 {tab==='my vehicles'&&<><form className="panel inline" onSubmit={e=>{e.preventDefault();act(async()=>{await req('/vehicles',{method:'POST',body:JSON.stringify({...form,userId:user.id})});F({})})}}><input required placeholder="Registration number" onChange={e=>set('number',e.target.value)}/><select onChange={e=>set('type',e.target.value)}><option>CAR</option><option>BIKE</option><option>EV</option></select><input placeholder="Model" onChange={e=>set('model',e.target.value)}/><button className="primary">Add vehicle</button></form>{vehicles.map(v=><article className="panel inline" key={v.id}><b>{v.number}</b><span>{v.type} · {v.model}</span><button className="outline" onClick={()=>act(()=>req('/vehicles/'+v.id,{method:'DELETE'}))}>Delete</button></article>)}</>}
 {(tab==='my bookings'||tab==='bookings')&&<div className="stack">{bookings.map(b=><Booking key={b.id} b={b} user={user} action={act}/>)}</div>}{tab==='users'&&<Users ownerId={user.id}/>}{tab==='slots'&&<AdminSlots location={form.selectedLocation} action={act}/>}
 </main></div>
}
function Booking({b,user,action}){return <article className="panel booking"><div><p className="eyebrow">{b.status}</p><h3>{b.parking_name} · Slot {b.slot_number}</h3><p>{b.vehicle_number||b.user_name} · {new Date(b.start_time).toLocaleString()}</p><p>Estimate ₹{b.estimated_amount} {b.final_amount&&`· Final ₹${b.final_amount}`}</p></div><div>{b.status==='CONFIRMED'&&user.role==='USER'&&<><button className="outline" onClick={()=>action(()=>req(`/bookings/${b.id}?userId=${user.id}`,{method:'DELETE'}))}>Cancel</button><button className="primary" onClick={()=>action(()=>req(`/sessions/check-in/${b.id}?userId=${user.id}`,{method:'POST'}))}>Check in</button></>}{b.status==='ACTIVE'&&<button className="primary" onClick={()=>action(()=>req(`/sessions/check-out/${b.id}?userId=${user.id}`,{method:'POST'}))}>Check out</button>}</div></article>}
function SlotPicker({location,user,vehicles,run}){const [slots,S]=useState([]),[choice,C]=useState(null),[vehicle,V]=useState(''),[start,A]=useState(''),[end,E]=useState(''),[maxRate,R]=useState(100);async function refresh(){if(location)S(await req(`/parking/locations/${location.id}/slots`))}useEffect(()=>{refresh()},[location]);return <><h2>{location?.name||'Select parking location'}</h2>{location&&<div className="panel"><div className="bar"><select onChange={e=>V(e.target.value)}><option value="">Choose vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.number} · {v.type}</option>)}</select><input type="datetime-local" onChange={e=>A(e.target.value)}/><input type="datetime-local" onChange={e=>E(e.target.value)}/><input type="number" placeholder="Max hourly rate" value={maxRate} onChange={e=>R(e.target.value)}/><button className="outline" onClick={()=>run(async()=>{const found=await req('/slots/recommend',{method:'POST',body:JSON.stringify({locationId:location.id,type:vehicles.find(v=>String(v.id)===String(vehicle))?.type,maxRate})});if(found[0])C(found[0].id);else throw Error('No suitable slot found')})}>Recommend</button></div><p className="legend">🟢 Available　🟡 Reserved　🔴 Occupied　⚫ Maintenance</p><div className="slots">{slots.map(s=><button key={s.id} disabled={s.status!=='AVAILABLE'} className={`slot ${choice===s.id?'chosen':''}`} onClick={()=>C(s.id)}>{s.number}<small>{s.type} · {s.status}</small></button>)}</div>{choice&&<button className="primary" onClick={()=>run(async()=>{if(!vehicle||!start||!end)throw Error('Choose vehicle, entry and exit times');await req('/bookings',{method:'POST',body:JSON.stringify({userId:user.id,vehicleId:vehicle,locationId:location.id,slotId:choice,startTime:start,endTime:end})});alert('Booking confirmed')})}>Confirm booking</button>}</div>}</>}
function AdminSlots({location,action}){const [slots,S]=useState([]),[number,N]=useState(''),[type,T]=useState('CAR');async function load(){if(location)S(await req(`/parking/locations/${location.id}/slots`))}useEffect(()=>{load()},[location]);return <><h2>{location?.name||'Choose a location from Manage Locations'}</h2>{location&&<><form className="panel inline" onSubmit={e=>{e.preventDefault();action(async()=>{await req('/admin/slots',{method:'POST',body:JSON.stringify({locationId:location.id,number,type})});N('');await load()})}}><input placeholder="Slot number e.g. A1" value={number} onChange={e=>N(e.target.value)}/><select onChange={e=>T(e.target.value)}><option>CAR</option><option>BIKE</option><option>EV</option></select><button className="primary">Add slot</button></form><div className="slots">{slots.map(s=><button className="slot" key={s.id} onClick={()=>action(async()=>{await req(`/admin/slots/${s.id}`,{method:'PUT',body:JSON.stringify({...s,status:s.status==='AVAILABLE'?'MAINTENANCE':'AVAILABLE'})});await load()})}>{s.number}<small>{s.type} · click to toggle {s.status}</small></button>)}</div></>}</>}
function Users({ownerId}){const [users,U]=useState([]);useEffect(()=>{req(`/admin/users?ownerId=${ownerId}`).then(U)},[ownerId]);return <div className="panel">{users.map(u=><p key={u.id}>{u.name} · {u.email} · {u.phone}</p>)}</div>}
