spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3307/smart_parking?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
server.port=8081
